improving tests and removing wait for image to scan on creation
aquasecurity/terraform-provider-aquasec pull request #144
Opened 2022-07-11 11:19 UTC by byteford

Adding the ability for tests to be run in parrel
removing the need for images to wait to be scanned when created.

2022-07-13 08:21 UTC, yossig-aquasec commented
@byteford can you please check yours changes in resource_permission_set_test it failing in the ci

2022-07-13 08:22 UTC, yossig-aquasec requested changes
please check the resource_permission_set_test

2022-07-13 12:12 UTC, byteford commented
> please check the resource_permission_set_test

should be fixed if you can rerun the tests

2022-07-13 12:24 UTC, yossig-aquasec approved these changes

2022-07-14 08:32 UTC, semyonmor approved these changes

2022-07-14 08:32 UTC, merged